#use this with `docker-compose up` against a generic Docker end-point (e.g. standalone Docker)
version: "2.1"

services:

  #yelb-ui:
  #  build: yelb-ui
  #  depends_on:
  #    - yelb-appserver
  #  ports:
  #    - 8080:80
  #  environment:
  #    - UI_ENV=dev # dev | test | prod 

  yelb-appserver:
    build: yelb-appserver
    depends_on: #- redis-server
      - yelb-db
    ports:
      - 4567:4567
    environment:
      - RACK_ENV=production # development | test | production 

  yelb-db: 
    build: yelb-db
    ports:
      - 5432:5432

  redis-server:
    image: public.ecr.aws/ubuntu/redis:6.0-21.04_edge
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes